### ISSUE TITLE
Cleaner error when failing to get GitHub info

### ISSUE THREAD

**Issue by rasmus** [rasmus/Bake#302]
```
Failed fetching pull request information
System.ArgumentNullException: Value cannot be null. (Parameter 'token')
   at Octokit.Ensure.ArgumentNotNull(Object value, String name) in /_/Octokit/Helpers/Ensure.cs:line 22
   at Octokit.Ensure.ArgumentNotNullOrEmptyString(String value, String name) in /_/Octokit/Helpers/Ensure.cs:line 32
   at Octokit.Credentials..ctor(String token, AuthenticationType authenticationType) in /_/Octokit/Http/Credentials.cs:line 32
   at Octokit.Credentials..ctor(String token) in /_/Octokit/Http/Credentials.cs:line 28
   at Bake.Services.GitHubClientFactory.CreateAsync(String token, Uri apiUrl, CancellationToken cancellationToken) in /home/runner/work/Bake/Bake/Source/Bake/Services/GitHubClientFactory.cs:line 41
   at Bake.Services.GitHub.CreateGitHubClientAsync(GitHubInformation gitHubInformation, CancellationToken cancellationToken) in /home/runner/work/Bake/Bake/Source/Bake/Services/GitHub.cs:line 151
   at Bake.Services.GitHub.GetPullRequestInformationAsync(GitInformation gitInformation, GitHubInformation gitHubInformation, CancellationToken cancellationToken) in /home/runner/work/Bake/Bake/Source/Bake/Services/GitHub.cs:line 97
   at Bake.Cooking.Ingredients.Gathers.GitHubGather.GatherAsync(Ingredients ingredients, CancellationToken cancellationToken) in /home/runner/work/Bake/Bake/Source/Bake/Cooking/Ingredients/Gathers/GitHubGather.cs:line 141
```

**Comment by rasmus** [comment]
Fixed already
